/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WS3D;

import main.Main;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

	@Test
	public void testAppHasAGreeting()
	{
		Main classUnderTest = new Main();
//		assertNotNull( "app should have a greeting", classUnderTest.main());
	}
}
